source "https://rubygems.org"

gem 'dotenv'

gem "sinatra"
gem "sinatra-cors"

# sinatra needs an app server
gem 'webrick'

gem "sentry-ruby"

group :test do
  gem "rack-test"
  gem "rspec"
  gem "rspec_junit_formatter"
end

gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"
