source "https://rubygems.org"

gem "sinatra"
gem "sinatra-cors"

gem "sentry-ruby"

gem "google-cloud-datastore"
gem "sinatra-activerecord"
gem "dotenv"

group :test do
  gem "rack-test"
  gem "rspec"
  gem "rspec_junit_formatter"
end