browsers:
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: Windows 10
- remote: true
  browserName: firefox
  browserVersion: latest
  platformName: Windows 10
- remote: true
  browserName: safari
  browserVersion: latest-1
  platformName: OS X 10.13
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: OS X 10.13

dsn: 'https://9802de20229e4afdaa0d60796cbb44d7@o87286.ingest.sentry.io/5390094'

# endpoints should NOT have "/" at the end
react_endpoints:
- https://application-monitoring-react-dot-sales-engineering-sf.appspot.com

vue_endpoints:
- https://application-monitoring-vue-dot-sales-engineering-sf.appspot.com
