mode: direct # events ingested directly into demo.sentry.io

browsers:
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: Windows 10
  param_display: chrome_windows 
- remote: true
  browserName: firefox
  browserVersion: latest
  platformName: Windows 10
  param_display: firefox_windows
- remote: true
  browserName: safari
  browserVersion: latest-1
  platformName: OS X 10.13
  param_display: safari_osx
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: OS X 10.13
  param_display: chrome_osx

dsn: 'https://9802de20229e4afdaa0d60796cbb44d7@o87286.ingest.sentry.io/5390094'

# endpoints should NOT have "/" at the end
react_endpoints:
- https://application-monitoring-react-dot-sales-engineering-sf.appspot.com

vue_endpoints:
- https://application-monitoring-vue-dot-sales-engineering-sf.appspot.com
