version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 0 # security updates only
    directory: '/'
    schedule:
      interval: daily
      timezone: America/Los_Angeles
      time: '16:00'
    reviewers:
      - '@sentry-demos/am-team'
    labels: []
    # Group dependency updates together in one PR
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    #groups:
      # The name of the group, it will be used in PR titles and branch
      #babel-dependencies:
        #patterns:
         # - '@babel/*'
    #ignore:
      #- dependency-name: '@sentry/node'
