steps:
- name: gcr.io/cloud-builders/docker
  args:
    - "build"
    - "-t"
    - "us.gcr.io/$PROJECT_ID/workspace_laravels_errors:$COMMIT_SHA"
    - "-t"
    - "us.gcr.io/$PROJECT_ID/workspace_laravels_errors:latest"
    - "-f"
    - "./Dockerfile"
    - "."

images:
- us.gcr.io/$PROJECT_ID/workspace_laravels_errors:$COMMIT_SHA
- us.gcr.io/$PROJECT_ID/workspace_laravels_errors:latest
