services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
