default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  database: <%= ENV.fetch("DB_DATABASE") %>

development:
  <<: *default
  host: "<%= ENV.fetch("DB_HOST") %>"
  port: "<%= ENV["DB_PORT"] %>"

# production will only work on Google Cloud App Engine
production:
  <<: *default
  host: "/cloudsql/<%= ENV.fetch("DB_CLOUD_SQL_CONNECTION_NAME") %>"
